version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/BuddyBridge
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  mongo-data: